### ISSUE TITLE
pick up the FLUX_PREFIX from env variable

### ISSUE THREAD

**Issue by JaeseungYeom** [flux-framework/dyad#7]
Instead of finding out where Flux is installed (i.e., `FLUX_PREFIX`) based on `$(prefix)/lib/pkgconfig`, use the env variable directly, and load pkgconf from `$(FLUX_PREFIX)/lib/pkgconfig`. This will require modifying  `config/ax_flux_core.m4` where `PKG_CONFIG_PATH` is set in `AX_FLUX_CORE` macro definition.
This allows using flux installed somewhere different from install destination.

**Comment by ilumsden** [comment]
The more traditional way of doing this is to just have the user prepend `$FLUX_PREFIX/lib/pkgconfig` to `PKG_CONFIG_PATH`. The `AX_FLUX_CORE` macro just uses pkg-config, so adding to `PKG_CONFIG_PATH` will cause flux-core to be found even if it's not in the same prefix as DYAD.

**Comment by JaeseungYeom** [comment]
That is a good solution.
